### DISCUSSION TITLE
Beta testing schemas for yaml input files

### DISCUSSION THREAD

**Discussion by gilrrei** [4C-multiphysics/4C#319] [Show and tell]
Thanks to @sebproell & friends, the exported metadata can already be used to validate Yaml files. Since the [schemas](https://json-schema.org/) are difficult to test, some beta testers are welcome. Download the newest version below . This should allow you to test autocomplete and validation of Yaml input files with the new sections in your IDE. If you come across issues or false validation, or you have an improvement in mind, comment below.

Sections that currently are not validated appear with `no schema` in their description. Here, you can pass anything.

# Updates
## v4
[test_schema.json](https://github.com/user-attachments/files/18940073/test_schema.json)

Last bug fixes, add noneable

## v3
[test_schema.json](https://github.com/user-attachments/files/18689140/test_schema.json)
### fixes
- result description and functions should be fixed

## v2
[test_schema.json](https://github.com/user-attachments/files/18673145/test_schema.json)
### fixes
- add missing sections
- make sections to array
### missing
- RESULT DESCRIPTION not validating correctly
## Orignal
[test_schema.json](https://github.com/user-attachments/files/18671834/test_schema.json)

# Usage 
Since I'm a VSCode user I'll add how to add the schema. If anybody uses a different editor feel free to add the instructions

## VSCode

- install [YAML by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)
- in your `settings.json` add:
  ```json
    "yaml.schemas": {
      "<path_to>/test_schema.json": "*.test.yaml",
    },
  ```
  the schema now automatically is applied on Yaml files that end with `.test.yaml`

**Comment by sebproell** [comment]
Here are the settings for CLion: 

![image](https://github.com/user-attachments/assets/369a658a-afb3-4a89-8773-346450e241e0)

**Comment by amgebauer** [comment]
Thanks for the schema @gilrrei!

Some sections are currently not recognized (e.g., `DSURF-NODE TOPOLOGY` and `NODE COORDS`)

Some sections take an array instead of a struct, e.g. `MATERIALS`, `FUNCT*`, `RESULT DESCRIPTION*`. I think these sections need to be `"type": "list"`

Here is an example input file:

```yaml
# Test of the templated implementation of solid elements
#
# Time Integration: Standard
# Shape: wedge6
# Element-Technology: shell_ans
# Fibers: none
PROBLEM TYPE:
  PROBLEMTYPE: Structure
DISCRETISATION:
  NUMSTRUCDIS: 1
SOLVER 1:
  NAME: Structure_Solver
  SOLVER: UMFPACK
STRUCTURAL DYNAMIC:
  LINEAR_SOLVER: 1
  INT_STRATEGY: Standard
  DYNAMICTYPE: GenAlpha
  NLNSOL: fullnewton
  PREDICT: ConstDis
  TIMESTEP: 0.5
  NUMSTEP: 2
  MAXTIME: 1
  TOLRES: 1.0E-12
  TOLDISP: 1.0E-12
MATERIALS:
  - MAT: 1
    MAT_ElastHyper:
      NUMMAT: 1
      MATIDS: [10]
      DENS: 0.1
  - MAT: 10
    ELAST_CoupNeoHooke:
      YOUNG: 10
      NUE: 0.25
FUNCT1:
  - COMPONENT: 0
    SYMBOLIC_FUNCTION_OF_SPACE_TIME: t
FUNCT2:
  - COMPONENT: 0
    SYMBOLIC_FUNCTION_OF_SPACE_TIME: (x+1)*(y+2)*(z+3)
RESULT DESCRIPTION:
  - STRUCTURE:
      DIS: structure
      NODE: 7
      QUANTITY: dispx
      VALUE: 1.77228378453625535e+00
      TOLERANCE: 1e-12
  - STRUCTURE:
      DIS: structure
      NODE: 7
      QUANTITY: dispy
      VALUE: -4.71792103220237957e-02
      TOLERANCE: 1e-12
  - STRUCTURE:
      DIS: structure
      NODE: 7
      QUANTITY: dispz
      VALUE: 7.41697807366413664e-01
      TOLERANCE: 1e-12
DESIGN SURF DIRICH CONDITIONS:
  - DSURF 1
  - E 1 - NUMDOF 3 ONOFF 1 1 0 VAL 0.0 0.0 0.0 FUNCT 0 0 0
DESIGN SURF NEUMANN CONDITIONS:
  - DSURF 1
  - E 2 - NUMDOF 6 ONOFF 1 1 1 0 0 0 VAL 10 0.01 0.01 0 0 0 FUNCT 1 2 2 0 0 0 TYPE Live
DSURF-NODE TOPOLOGY:
  - NODE 1 DSURFACE 1
  - NODE 8 DSURFACE 1
  - NODE 5 DSURFACE 1
  - NODE 4 DSURFACE 1
  - NODE 7 DSURFACE 2
  - NODE 2 DSURFACE 2
  - NODE 6 DSURFACE 2
  - NODE 3 DSURFACE 2
NODE COORDS:
  - NODE 1 COORD 0.0 0.0 0.0
  - NODE 2 COORD 1.0 0.0 0.0
  - NODE 3 COORD 1.0 1.0 0.0
  - NODE 4 COORD 0.0 1.0 0.0
  - NODE 5 COORD 0.0 0.0 1.0
  - NODE 6 COORD 1.0 0.0 1.0
  - NODE 7 COORD 1.0 1.0 1.0
  - NODE 8 COORD 0.0 1.0 1.0
STRUCTURE ELEMENTS:
  - 1 SOLID WEDGE6 1 3 4 5 7 8 MAT 1 KINEM nonlinear TECH shell_ans
  - 2 SOLID WEDGE6 5 7 6 1 3 2 MAT 1 KINEM nonlinear TECH shell_ans
```
