### ISSUE TITLE
Add a metadata section in the input files

### ISSUE THREAD

**Issue by amgebauer** [4C-multiphysics/4C#48]
_Issue copied from Gitlab. Original issue is [here](https://gitlab.lrz.de/baci/baci/-/merge_requests/2643)._

## Description
The following discussion emerged in [!2643](https://gitlab.lrz.de/baci/baci/-/merge_requests/2643):

- [ ] @sebproell started a [discussion](https://gitlab.lrz.de/baci/baci/-/merge_requests/2643#note_3429457):  (+5 comments)

    > We might want to remove this section and simply use comments.

I propose to add a metadata section to the 4C input, here a yaml example (of course also works in .dat format):
```yaml
TITLE: Some example input file
METADATA:
  4C COMMIT SHA: 9e7e29b9f6b7ee3826c8fb85649b022152276ac4
  UNIT SYSTEM: mm s kg C nmol
  MESHPY:
    Date: 2024-11-12 16:47:05
    Script used to create input file:
      path: <thanks_ivo_for_the_metadata_example_from_meshpy>.py
      git sha: 9ce6e5cceb72f1cf023dab7d1c49b4063d7a77ae
      git date: 2024-11-12 16:27:28 +0100
    Input file created with meshpy:
      git sha: 7d6fcf0f4926eaea7c76f6e427a1f39a495e9e14
      git date: 2024-11-12 11:51:44 +0100
    The module cubitpy was loaded:
      git sha: a2e12fa1b74da5972b2abac8183cc70b23d84a01
      git date: 2024-11-11 12:08:15 +0100
  QUEENS:
    job_id: 5
    parameters:
      diff_am: 5.337275108755453e-12
      cond_el: 16.837766870089055
      ex_curr_dens_an_el: 0.0005322132511515822
      ex_curr_dens_ed_el: 0.000581558952350122
      c_rate: 0.1101580102636539
      separator_thickness: 365.2769378965071
      cathode_thickness_number_of_particles: 9.61506741886947
IO:
  STRUCT_STRAIN: gl
```
### What metadata? 
- All the information a user would want to write to the input file!
- For example how it was created (as similarly done by `pre_exodus`). This examples includes meshpy information (@istein thanks for the meshpy metadata examples), QUEENS inputs as well as information on the unit system (@davidrudlstorfer could be used with pytoda) 
- All the information in here is **not** to be used for any 4C parameters\run settings\config
- I propose to make this section a dict (object from the schema POV) in order to make it a simple hierarchical nested structure

### Why not simply use comments?
 - Comments mean that the information can not be loaded in again with a standard reader (e.g. pyyaml) which would lead to additional implementation effort to add the comments
 - Creating a section allows to print it out in the 4C run log (discussed with @amgebauer) with only a small amount of implementational effort
 - In the input generators (meshpy, lnmeshio, pytoda, QUEENS) the metadata can be nested (call pytoda in QUEENS in combination with lnmeshio) and still be exported with a standard yaml tool

### Why add a new section?
- This section would closely resemble the title section, in the sense that the information in here is not used. Since the data can be more general I propose to add a new section or include the title section within the metadata section. I slightly prefer the latter solution but I think both are fair
- As mentioned above printing out this section once in the beginning of a 4C run increases usability through sanity checks (from my biased POV this is especially useful in MQA settings since from the log I could identify what the inputs were)
- An important feature of this section would be that it can be defined in every file listed in the `INCLUDES` section. Consequently this section could/should appear more than once!

## Possible Solution and Definition of Done
¯\＿(ツ)＿/¯

## Related Issues and Merge Requests
* Blocks
* Is blocked by
* Follows !2643 
* Precedes
* Related to
* Part of
* Composed of

## Additional Information
Thanks @amgebauer @davidrudlstorfer  @isteinbrecher  for the input on this
