### ISSUE TITLE
Allow to read the mesh from standard mesh formats

### ISSUE THREAD

**Issue by amgebauer** [4C-multiphysics/4C#60]
## Description

The mesh should not be part of the input file. Instead, it should be directly read from a (standard) mesh format.

Materials and other element properties could then be specified for blocks instead for each element, e.g. (suppose we have a yaml input file):

```yaml
element_blocks:
    name_of_block:
        MAT: 1
        KINEM: nonlinear
        EAS: none
        ELEMENT: SOLID
```

The mesh-format that we then read must be able to have some requirements:

 * should be a standard format (exodus, gmsh, xdmf, ...)
 * nodesets / sidesets for boundary conditions
 * element and nodal data for fiber directions
 * reasonably fast to read in a mesh and distribute it in parallel. This may either include parallel reading or a better implementation of parallel communication.

## Possible Solution and Definition of Done

- [ ] Decide on a format
- [ ] Check which library to use to read the mesh

## Related Issues and Merge Requests

* Blocks
* Is blocked by
* Follows
* Precedes
* Related to
* Part of
* Composed of
